### ISSUE TITLE
How to use this ?

### ISSUE THREAD

**Issue by AbhayGhante** [jiunnhwa/MT4TradeCopier#1]
Confused about how to deploy it.

**Comment by AbhayGhante** [comment]
Please Reply

**Comment by jiunnhwa** [comment]
This is the trade copier console program. It will poll the master folder for trades, and then copies it to the slaves folder.
The MT4 master terminal runs an EA to that writes to the master folder when there are trades changes, such as new trade executed on master MT4.
The slaves MT4 terminals will also run an EA to read these trade changes and mimic the master's actioin.

**Comment by AbhayGhante** [comment]
But how to use this?
